title: Zil E Huma # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Data Enthusiast and Master in Information System Student</b>
  <br>
  I have a professional work portfolio that spans almost 1.5 years in the field of data and business analysis. My areas of experience include data analysis, data visualization, and business dashboards. Furthermore, I am also doing master’s in computer science in the domain of Information System.
  <br>
  <a href="https://github.com/muhammadtoqeerzafar/muhammadtoqeerzafar.github.io/blob/main/pdf/Resume.pdf">Resume</a>| 
  <a href="https://www.credly.com/users/muhammad-toqeer-zafar.64b64112/badges">Certifications</a> 
  <br> <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
