  
title: <p align="center"> Muhammad Toqeer Zafar </p>

logo: "/images/photo.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/muhammadtoqeerzafar/">LinkedIn</a> |
  
  </p>
  
  <p align="justify"> # your text below (remove <br> elements if you don't need line breaks)
  <b>Data Enthusiast</b>
  <br><br>
  I have recently completed my Masters in Physics from University of Siegen and an Entry level position in data analytics is what I have set my eyes on.
  <br><br>
  <a href="https://www.linkedin.com/in/muhammadtoqeerzafar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
