title: Muhammad Toqeer Zafar # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Data Enthusiast</b>
  <br>
  I'm a datascience aspirant having Masters degree from University of Siegen as well as Data Analytics Professional Certificate from Google. I am seeking an entry level position to leverage my diverse data analytics skills obtained through my academic and professional career.
  <br><br>
  <a href="https://www.linkedin.com/in/muhammadtoqeerzafar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
